- name: Clone dotfiles
  ansible.builtin.git:
    repo: https://github.com/chrisbradleydev/dotfiles
    dest: "$HOME/.dotfiles"
    version: linux

- name: Make ~/.config directory
  ansible.builtin.file:
    path: "$HOME/.config"
    state: directory
    mode: "0755"

- name: Symlink sheldon directory
  ansible.builtin.file:
    src: "$HOME/.dotfiles/{{ item.src }}"
    dest: "$HOME/{{ item.dest }}"
    state: link
  with_items: "{{ debian_symlinks }}"
