---
kubernetes_ciuser: # cloud-init user
kubernetes_sshkey: ""
kubernetes_kube_version: "v1.33"
kubernetes_cri_o_version: "1.33.2-1.1"
kubernetes_kubeadm_version: "1.33.2-1.1"
kubernetes_kubectl_version: "1.33.2-1.1"
kubernetes_kubelet_version: "1.33.2-1.1"
