home:
  hosts:
    pve1.localdomain:
      ansible_host: 192.168.1.11
      ansible_port: 22
      ansible_user: root
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    pve2.localdomain:
      ansible_host: 192.168.1.12
      ansible_port: 22
      ansible_user: root
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    kube1.localdomain:
      ansible_host: 192.168.1.70
      ansible_port: 22
      ansible_user: chrisbradley
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    localhost:
      ansible_connection: local

all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
