home:
  hosts:
    # vlan 10
    moby.localdomain:
      ansible_host: 192.168.10.11
      ansible_port: 22
      ansible_user: chrisbradley
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    # vlan 20
    pve1.localdomain:
      ansible_host: 192.168.20.11
      ansible_port: 22
      ansible_user: root
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    pve2.localdomain:
      ansible_host: 192.168.20.12
      ansible_port: 22
      ansible_user: root
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    # vlan 30
    kube1.localdomain:
      ansible_host: 192.168.30.11
      ansible_port: 22
      ansible_user: chrisbradley
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    kube2.localdomain:
      ansible_host: 192.168.30.12
      ansible_port: 22
      ansible_user: chrisbradley
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    kube3.localdomain:
      ansible_host: 192.168.30.13
      ansible_port: 22
      ansible_user: chrisbradley
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    localhost:
      ansible_connection: local

all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
