# https://github.com/cilium/cilium/blob/main/install/kubernetes/cilium/values.yaml

bgpControlPlane:
  # Enables the BGP control plane
  enabled: true

cni:
  # Make Cilium take ownership over the `/etc/cni/net.d` directory on the node
  exclusive: false

hubble:
  # Enable Hubble
  enabled: true

ipam:
  # Configure IP Address Management mode
  # https://docs.cilium.io/en/stable/network/concepts/ipam/
  mode: "cluster-pool"
  operator:
    # IPv4 CIDR list range to delegate to individual nodes for IPAM
    clusterPoolIPv4PodCIDRList: ["10.0.0.0/8"]

# Kubernetes service host & port
k8sServiceHost: "192.168.30.11"
k8sServicePort: "6443"

# https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/
kubeProxyReplacement: "true"

l2announcements:
  # Enable L2 announcements
  enabled: false

# Roll out cilium agent pods automatically when configmap is updated
rollOutCiliumPods: true

socketLB:
  # Ensure Cilium does not interfere with Istio
  # https://docs.cilium.io/en/latest/network/servicemesh/istio/
  hostNamespaceOnly: true
