- name: Check if containerd is already installed
  ignore_errors: true
  ansible.builtin.command: containerd --version
  register: containerd_installed

- name: Set containerd kernal modules
  become: true
  ansible.builtin.blockinfile:
    path: /etc/modules-load.d/modules.conf
    block: |
      br_netfilter
      overlay
  when: containerd_installed.failed

- name: Add modules
  become: true
  ansible.builtin.shell:
    cmd: |
      modprobe br_netfilter
      modprobe overlay
  when: containerd_installed.failed

- name: Check modules
  ansible.builtin.shell:
    cmd: |
      lsmod | grep br_netfilter
      lsmod | grep overlay
  register: checkModules
  when: containerd_installed.failed

- name: Verify modules are loaded
  ansible.builtin.assert:
    that:
      - "'br_netfilter' in checkModules.stdout"
      - "'overlay' in checkModules.stdout"
  when: containerd_installed.failed

- name: Install dependencies
  become: true
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
  when: containerd_installed.failed

- name: Add Docker's official GPG key
  become: true
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    dest: /etc/apt/keyrings/docker.asc
  when: containerd_installed.failed

- name: Get CPU architecture
  ansible.builtin.command: dpkg --print-architecture
  register: arch
  when: containerd_installed.failed

- name: Get release name
  ansible.builtin.command: lsb_release -cs
  register: release
  when: containerd_installed.failed

- name: Add Docker apt repo
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ arch.stdout }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ release.stdout }} stable"
    state: present
    filename: docker
  when: containerd_installed.failed

- name: Install containerd
  become: true
  ansible.builtin.apt:
    update_cache: true
    name: containerd.io
  when: containerd_installed.failed

- name: Get containerd config
  ansible.builtin.shell: containerd config default
  register: containerd_conf
  when: containerd_installed.failed

- name: Set containerd config
  ansible.builtin.copy:
    content: "{{ containerd_conf.stdout }}"
    dest: /etc/containerd/config.toml
  when: containerd_installed.failed
